SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_NATIONALBANK = 3
SOURCE_VKURSE = 4
SOURCE_PUMB = 5

SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_NATIONALBANK, 'NationalBank'),
    (SOURCE_VKURSE, 'Vkurse'),
    (SOURCE_PUMB, 'Pumb'),
)

CURRENCY_TYPE_USD = 1
CURRENCY_TYPE_EUR = 2
CURRENCY_TYPE_CHOICES = (
    (CURRENCY_TYPE_USD, 'USD'),
    (CURRENCY_TYPE_EUR, 'EUR'),
)

RATE_TYPE_SALE = 1
RATE_TYPE_BUY = 2
RATE_TYPE_CHOICES = (
    (RATE_TYPE_SALE, 'Sale'),
    (RATE_TYPE_BUY, 'Buy'),
)
