# Generated by Django 2.2.12 on 2020-06-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'),
                                                            (2, 'MonoBank'),
                                                            (3, 'NationalBank'),
                                                            (4, 'Vkurse'),
                                                            (5, 'Pumb')]),
        ),
    ]
